import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/app/NavBar";
import Footer from "./footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet" />
      </head>
      <body className="min-h-screen">
        <div className="relative">
          <div className="fixed top-0 left-0 right-0 bg-[#f2f2f2]">
            <NavBar></NavBar>
          </div>
        </div>
        <div className="py-20 bg-[#27413e]">
          {children}
        </div>
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
